/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'createNote' : IDL.Func([IDL.Text], [Note], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'editNote' : IDL.Func([IDL.Nat, IDL.Text], [Note], []),
  'getNextNotification' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'processNotifications' : IDL.Func([], [Time], []),
  'setBreakReminder' : IDL.Func([IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'createNote' : IDL.Func([IDL.Text], [Note], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'editNote' : IDL.Func([IDL.Nat, IDL.Text], [Note], []),
    'getNextNotification' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'processNotifications' : IDL.Func([], [Time], []),
    'setBreakReminder' : IDL.Func([IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };